services: 
  app: 
    build:
      context: .  
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - mysql-service
  
  mysql-service:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=template
    volumes:
      - mysql-service-data:/var/lib/mysql

volumes:
  mysql-service-data:
  